# Generated by Django 4.1.5 on 2023-01-09 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0004_room_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amenity",
            options={"verbose_name_plural": "Amenities"},
        ),
        migrations.RenameField(
            model_name="room",
            old_name="print",
            new_name="price",
        ),
    ]
