# Generated by Django 4.1.5 on 2023-01-09 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0005_alter_amenity_options_rename_print_room_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="toilts",
            new_name="toilets",
        ),
    ]
