# Generated by Django 4.1.5 on 2023-01-15 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0003_remove_perk_category_experience_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="experience",
            old_name="start_at",
            new_name="start",
        ),
    ]
