# Generated by Django 4.1.4 on 2023-02-20 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0003_alter_photo_file_alter_video_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='descriptions',
            new_name='description',
        ),
    ]
