# Generated by Django 4.1.5 on 2023-02-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0007_room_category_alter_room_amenities_alter_room_owner"),
        ("wishlists", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlist",
            name="rooms",
            field=models.ManyToManyField(
                blank=True, related_name="wishlist", to="rooms.room"
            ),
        ),
    ]
