# Generated by Django 4.1.5 on 2023-02-21 02:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wishlists", "0003_alter_wishlist_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wishlist",
            old_name="rooms",
            new_name="room",
        ),
    ]
